### ISSUE TITLE
Compatible with Immutable JS?

### ISSUE THREAD

**Issue by CRielsky** [mogest/sorted-immutable-list#2]
Passing an Immutable JS List causes the accumulator to hang and freeze. Is Immutable JS not supported by this library?

**Comment by mogest** [comment]
Hi @CRielsky. No, it only works with plain arrays. ImmutableJS already has sorting built in, this library is more for people who don't want to go all in on ImmutableJS.

**Comment by CRielsky** [comment]
Hi Roger,

I'm  junior dev so I'm fairly unfamiliar how does the Immutable list
already have sorting built in?

Thanks,
Conner

**Comment by mogest** [comment]
All good. Here's a page I found that shows how you can use immutableJS to sort all sorts of things: https://github.com/facebook/immutable-js/blob/master/__tests__/sort.ts.

Here's also the docs on List.sort: http://devdocs.io/immutable/index#list.sort

Hope that helps.
